-- PostgreSQL schema for the "寻根溯源" genealogy management system.
-- Run in an empty database, for example:
--   psql -U postgres -d genealogy_db -f sql/01_schema.sql

DROP TABLE IF EXISTS marriages CASCADE;
DROP TABLE IF EXISTS parent_child CASCADE;
DROP TABLE IF EXISTS members CASCADE;
DROP TABLE IF EXISTS tree_collaborators CASCADE;
DROP TABLE IF EXISTS family_trees CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_users_username_len CHECK (length(trim(username)) >= 3)
);

CREATE TABLE family_trees (
    tree_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_name VARCHAR(120) NOT NULL,
    surname VARCHAR(30) NOT NULL,
    revision_time DATE,
    creator_user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_family_trees_name_len CHECK (length(trim(tree_name)) > 0),
    CONSTRAINT chk_family_trees_surname_len CHECK (length(trim(surname)) > 0)
);

CREATE TABLE tree_collaborators (
    tree_id BIGINT NOT NULL REFERENCES family_trees(tree_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    role VARCHAR(16) NOT NULL DEFAULT 'editor',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tree_id, user_id),
    CONSTRAINT chk_tree_collaborators_role CHECK (role IN ('owner', 'editor', 'viewer'))
);

CREATE TABLE members (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_id BIGINT NOT NULL REFERENCES family_trees(tree_id) ON DELETE CASCADE,
    name VARCHAR(80) NOT NULL,
    gender CHAR(1) NOT NULL,
    birth_year INT NOT NULL,
    death_year INT,
    generation INT NOT NULL,
    biography TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_members_name_len CHECK (length(trim(name)) > 0),
    CONSTRAINT chk_members_gender CHECK (gender IN ('M', 'F')),
    CONSTRAINT chk_members_birth_year CHECK (birth_year BETWEEN 1000 AND 2200),
    CONSTRAINT chk_members_death_year CHECK (death_year IS NULL OR death_year >= birth_year),
    CONSTRAINT chk_members_generation CHECK (generation >= 1)
);

CREATE TABLE parent_child (
    parent_id BIGINT NOT NULL REFERENCES members(member_id) ON DELETE CASCADE,
    child_id BIGINT NOT NULL REFERENCES members(member_id) ON DELETE CASCADE,
    relation_type VARCHAR(12) NOT NULL,
    PRIMARY KEY (parent_id, child_id),
    CONSTRAINT chk_parent_child_type CHECK (relation_type IN ('father', 'mother')),
    CONSTRAINT chk_parent_child_not_self CHECK (parent_id <> child_id),
    CONSTRAINT uq_parent_child_one_parent_type UNIQUE (child_id, relation_type)
);

CREATE TABLE marriages (
    marriage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_id BIGINT NOT NULL REFERENCES family_trees(tree_id) ON DELETE CASCADE,
    spouse1_id BIGINT NOT NULL REFERENCES members(member_id) ON DELETE CASCADE,
    spouse2_id BIGINT NOT NULL REFERENCES members(member_id) ON DELETE CASCADE,
    marriage_year INT,
    CONSTRAINT chk_marriages_not_self CHECK (spouse1_id <> spouse2_id),
    CONSTRAINT chk_marriages_canonical_pair CHECK (spouse1_id < spouse2_id),
    CONSTRAINT chk_marriages_year CHECK (marriage_year IS NULL OR marriage_year BETWEEN 1000 AND 2200),
    CONSTRAINT uq_marriages_pair UNIQUE (tree_id, spouse1_id, spouse2_id)
);

CREATE OR REPLACE FUNCTION validate_parent_child()
RETURNS trigger AS $$
DECLARE
    parent_record members%ROWTYPE;
    child_record members%ROWTYPE;
BEGIN
    SELECT * INTO parent_record FROM members WHERE member_id = NEW.parent_id;
    SELECT * INTO child_record FROM members WHERE member_id = NEW.child_id;

    IF parent_record.tree_id <> child_record.tree_id THEN
        RAISE EXCEPTION 'parent and child must belong to the same family tree';
    END IF;

    IF NEW.relation_type = 'father' AND parent_record.gender <> 'M' THEN
        RAISE EXCEPTION 'father relation requires a male parent';
    END IF;

    IF NEW.relation_type = 'mother' AND parent_record.gender <> 'F' THEN
        RAISE EXCEPTION 'mother relation requires a female parent';
    END IF;

    IF parent_record.birth_year >= child_record.birth_year THEN
        RAISE EXCEPTION 'parent birth year must be earlier than child birth year';
    END IF;

    IF parent_record.generation >= child_record.generation THEN
        RAISE EXCEPTION 'parent generation must be earlier than child generation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validate_parent_child
BEFORE INSERT OR UPDATE ON parent_child
FOR EACH ROW EXECUTE FUNCTION validate_parent_child();

CREATE OR REPLACE FUNCTION validate_marriage()
RETURNS trigger AS $$
DECLARE
    spouse1_record members%ROWTYPE;
    spouse2_record members%ROWTYPE;
BEGIN
    SELECT * INTO spouse1_record FROM members WHERE member_id = NEW.spouse1_id;
    SELECT * INTO spouse2_record FROM members WHERE member_id = NEW.spouse2_id;

    IF spouse1_record.tree_id <> NEW.tree_id OR spouse2_record.tree_id <> NEW.tree_id THEN
        RAISE EXCEPTION 'both spouses must belong to the marriage family tree';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validate_marriage
BEFORE INSERT OR UPDATE ON marriages
FOR EACH ROW EXECUTE FUNCTION validate_marriage();
